server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dorm_manage?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*